version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: task-manager-poc-container
    environment:
      POSTGRES_DB: task-manager-poc
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"
