version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: task-manager-poc-container
    environment:
      POSTGRES_DB: task-manager-poc
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"


  flyway:
    image: flyway/flyway
    command: [ "-url=jdbc:postgresql://postgres:5432/task-manager-poc", "-user=local", "-password=local", "migrate" ]
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - postgres
    networks:
      - task-manager-poc

networks:
  task-manager-poc:
    driver: bridge
